### ISSUE TITLE
When adding a person, the page heading should say "Add Person"

### ISSUE THREAD

**Issue by sgmurphy** [sgmurphy/the-scheduler#7]

**Comment by knmurphy** [comment]
I attempted this in a similar way as I solved #8 but ran into errors relating to the actions etc. Got an error about the action not being found on the route. Tried to further solve via https://github.com/DockYard/ember-route-action-helper and had some traction but the bindings to the model were off some how (I think). I removed it all cause it didn't work.

**Comment by sgmurphy** [comment]
The approach I suggested on #8 should work here too:
`<span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{if model.isNew 'Add' 'Edit'}} Person`
