### ISSUE TITLE
When adding a group, the page heading should say "Add Group"

### ISSUE THREAD

**Issue by sgmurphy** [sgmurphy/the-scheduler#8]

**Comment by knmurphy** [comment]
@sgmurphy probably deserves a look incase I didn't do it right

**Comment by sgmurphy** [comment]
A simpler solution that would allow us to continue using the same route, controller, and template for adding and editing would look like this:
`<span class="glyphicon glyphicon-tag" aria-hidden="true"></span> {{if model.isNew 'Add' 'Edit'}} Group`
